name: Deploy Documentation

on:
  push:
    branches:
      - main # Trigger deploy when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0" # Adjust the version if necessary

      - name: Install DocFX tool
        run: |
          dotnet tool install -g docfx
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Build documentation with DocFX
        run: docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages # Deploy to the gh-pages branch
