name: Deploy DocFX Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x" # Use compatible .NET SDK version for DocFX

      - name: Install DocFX
        run: |
          dotnet tool install -g docfx
          echo "::add-path::$(dotnet tool path)"

      - name: Build DocFX documentation
        run: docfx docfx_project/docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docfx_project/_site
          publish_branch: main # Deploy directly to the main branch
